# code: language=Ansible insertSpaces=true tabSize=2


- name: Assertions
  assert:
    that:
      # K8S master node
      - k8s_primary_master_name is defined
      # Provider
      - ceph_client_k8s_provider | default('') | length > 0
      # K8S - StorageClass
      - ceph_client_k8s_sc_namespace | default('') | length > 0
      - ceph_client_k8s_sc_name | default('') | length > 0
      - ceph_client_k8s_mons | default('') | length > 0 or not 'apply' in ansible_run_tags
      - ceph_client_k8s_pool | default('') | length > 0 or not 'apply' in ansible_run_tags
      # K8S - Secret
      - ceph_client_k8s_secret_namespace | default('') | length > 0
      - ceph_client_k8s_secret_name | default('') | length > 0
      - ceph_client_k8s_user | default('') | length > 0 or not 'apply' in ansible_run_tags
      - ceph_client_k8s_key | default('') | length > 0 or not 'apply' in ansible_run_tags
  when:
    - inventory_hostname == k8s_primary_master_name
  tags: [always]


- name: Include provider tasks
  include_tasks:
    file: "provider-{{ ceph_client_k8s_provider }}.yml"
  when:
    - inventory_hostname == k8s_primary_master_name
  tags: [never, apply, delete]
